---
#postgresql_version: "9.2"
#postgresql_data_dir: "/var/lib/pgsql/data"
#postgresql_bin_path: "/usr/bin"
#postgresql_config_path: "/var/lib/pgsql/data"
#postgresql_daemon: postgresql
#postgresql_packages:
#  - postgresql
#  - postgresql-server
#  - postgresql-contrib
#  - postgresql-libs

postgresql_data_dir: "/var/lib/pgsql/{{postgresql_version}}/data"
postgresql_download_path: "/tmp"
postgresql_config_path: "{{postgresql_data_dir}}"
